### ISSUE TITLE
No direct way to disable email in Docker container

### ISSUE THREAD

**Issue by jamesderlin** [smkent/safeway-coupons#88]
With 0.2.1 depending on Chrome and Selenium, I switched from PyPI installation to the Docker one.  However, I noticed:

1. There doesn't seem to be a direct way to disable sendmail usage from `docker-compose.yaml`.  While I'm a fan of email notifications, I don't have an SMTP host that doesn't require authentication. (Or maybe there's some way to authenticate?  This isn't very clear.) It perhaps would be nice if there were some `EXTRA_ARGS` environment variable with the explicit purpose of passing arbitrary arguments to `safeway-coupons`.
2. You already can pass arbitrary arguments to `safeway-coupons` via a hack:
    ```yaml
    services:
      safeway-coupons:
        environment:
          SAFEWAY_ACCOUNTS_FILE: /accounts_file --no-email
    ```
   which indicates that `SAFEWAY_ACCOUNTS_FILE` is not being properly quoted when generating the container's crontab.
3. Unrelated, but the `docker-compose.yaml` example in `README.md` should clarify that `CRON_SCHEDULE` is setting `safeway-coupons` to run at 2:00 AM *UTC* each day and that `TZ` should be set for scheduling it according to your local timezone.
